config/routes.rb
Radddar::Application.routes.draw do

  root :to => "app#landing"
  match '/reminder', :to => "app#reminder", :as => "reminder"

  match '/app', :to => "app#app", :as => "app"
  match '/live', :to => "app#live", :as => "live"

  match '/auth/:provider/callback', :to => 'sessions#callback', :as => "auth"
  match '/signout', :to => 'sessions#destroy', :as => 'signout'
  match '/auth', :to => "sessions#pusher_auth", :as => "pusher_auth"

  match '/current_user', :to => "app#current_user_action", :as => "current_user"
  match '/profile_update', :to => "app#profile_update", :as => "profile_update"
  
  match '/status_form', :to => "app#status_form", :as => "status_form"
  match '/status_set', :to => "app#status_set", :as => "status_set"
  match '/status_reload', :to => "app#status_reload", :as => "status_reload"

  match '/share/location/:provider', :to => "app#share_location", :as => "share_location"

  match '/profile/:id', :to => "app#profile", :as => "profile"
  match '/swap', :to => "app#swap", :as => "swap"

  match '/notify/:id', :to => "app#notify", :as => "notify"
  match '/remove_note/:stamp', :to => "app#remove_note", :as => "remove_note"

  match '/reload_chat_feed', :to => "app#reload_chat_feed", :as => "reload_chat_feed"
  
  match '/chat/:id', :to => "app#chat", :as => "chat"
  match '/message/:id', :to => "app#message", :as => "message"

  match '/reload_clients/:key', :to => "app#reload_clients", :as => "reload_clients"

  match '/wisdom-script.ttf', :to => "app#wisdom_script"
  match '/steelfish.ttf', :to => "app#steelfish"

  match '/:id', :to => "app#public_radddar", :as => "public_radddar"

end

app/models/user.rb
# For more special queries please read:
# http://stackoverflow.com/questions/7702244/mongodb-with-mongoid-in-rails-geospatial-indexing

Mongoid.autocreate_indexes = true

class User
  include Mongoid::Document
  include Mongoid::Timestamps

  extend ActiveSupport::Concern
  include ActionView::Helpers::NumberHelper

  include ApplicationHelper

  # First name if facebook / username if twitter
  field :name, :type => String

  # This field are from providers if they are not set
  field :image_custom, :type => String
  field :birthday_custom, :type => Date
  field :gender_custom, type: String, default: -> { "none" }

  field :email, :type => String

  # loc holds last location that user provided
  field :loc, type: Array
  index [[ :loc, Mongo::GEO2D ]]

  # Range of my swap (200m default)
  field :swap_range, type: Integer, default: -> {
	  User.allowed_swap_ranges.last
  }

  # Field status
  field :status, type: String

  before_save :move_away_from_others

  # Allowed swap ranges for #swap_range
  def self.allowed_swap_ranges
    if Rails.env =~ /(production|development)/
      [1000, 20000, 600000, 900000 ]
    else # For testing the last range should be smaller.
      [200, 1000, 20000, 200000 ] #m 200000
    end
  end

  # Return name as string
  define_method(:to_s) {
    return "#{self.name}"
    #age==0? "#{self.name}": "#{self.name}, #{age}"
  }

  def w_age
    age==0? "#{self.name}": "#{self.name}, #{age}"    
  end

  scope :box, ->(loc_a, loc_b) {
	  User.where(:loc => {
		  "$within" => {
			  "$box" => [
				  loc_b, loc_a
			  ]
			}
		}).where(:updated_at.gt => 7.days.ago)
	}

  embeds_many :providers

  validates_length_of :status, :maximum => 140,
  	:allow_nil => true,
  	:allow_blank => true,
  	:message => "can't be longer than 140 characters!"
  
  validates_inclusion_of :swap_range,
  	:in => User.allowed_swap_ranges,
  	:message => "range is not allowed!"

#  included do
#      self.send(:distance)
#      self.send(:distance_to_human)
#  end

  # Distance from origin point
  def distance
    return 0 if self.loc == @@current_loc
    return 0 if self.loc.nil? or @@current_loc.nil?
    haversine_distance(@@current_loc,self.loc)
  end

  # Distance in human words
  def distance_to_human
    number_to_human(distance.to_i,:units => :distance_short).to_s
  end

  def distance_between user
    return 0 if self.loc == user.loc
    haversine_distance(self.loc, user.loc)
  end

  def distance_between_to_human user
    number_to_human(distance_between(user).to_i,:units => :distance_short).to_s
  end

  # Swap around user
  @@current_loc = nil
  def swap range=nil #m
  	range = self.swap_range unless !range.nil?

  	raise "Range: #{range} - is not allowed range!" unless range.in? User.allowed_swap_ranges

    # Return [] if location is null..
    return [] if self.loc.nil? || self.loc == ""

  	@@current_loc=self.loc

    self.send(:distance)
    self.send(:distance_to_human)

    User.where(:loc => {
    "$within" => {
        "$centerSphere" => [self.loc, ((range.fdiv(1000)).fdiv(6371))]
      }
    }).where(:updated_at.gt => 72.hours.ago) # 24h!
  end

  # Convert gender hash into words
  def self.stat_to_human stats
    return "Nobody is around you." if stats[:none]==0 and stats[:male] == 0 and stats[:female] == 0
      
    pom_str = []
    stats = stats.select {|v| stats[v]>0 }

    stats.keys.each do |key|
      pom_str<< "#{stats[key]} #{User.none_to_ufo(key)}" if stats[key] == 1
      pom_str<< "#{stats[key]} #{User.none_to_ufo(key.to_s).pluralize}" if stats[key] > 1
    end

    pom_str_v = pom_str.join(" and ")

    are_is = "are"
    are_is = "is" if pom_str.size == 1 or stats.first[1] == 1
    are_is = "are" if stats.first[1] > 1

    #OLD out = "There #{are_is} #{pom_str_v} around you."
    out = "#{pom_str_v} around you."

    
    m = out.scan(/(\ and\ \d+\ \w+)/i).flatten.compact.uniq  
    
    out.gsub! m.first, m.first.gsub(" and",",") if m.size > 1 
    
    out 
  end

  # Do the stat lookup
  def swap_stat range=nil
    users = self.swap(range).select {|u| u.id != self.id}
    stats = {female: 0,male: 0,none: 0}

    stats.keys.each do |key|
      stats[key] = users.to_a.inject(0) do |sum,v|
        s_key = key.to_s
        s_key = nil if key.to_s=="none"
        if v.gender==s_key
          sum + 1
        else
          sum + 0
        end
      end
    end

    User.stat_to_human stats
  end


  def self.none_to_ufo(value)
    value = "boy" if value.to_s=="male"
    value = "girl" if value.to_s=="female"
    return "UFO" if value.to_s == "none"
    value
  end

  # See chat with someone
  def chat_with user, limit=20
    from_to_stamp = ["#{self.id}-#{user.id}","#{user.id}-#{self.id}"]
    Message.where(:from_to_stamp.in => from_to_stamp).order_by([:created_at,:desc]).limit(limit)
  end

  # List of chats
  def chats
    # Find message exchanges
    message_pairs = Message.where('$or' => [{"sender_id" => self.id},{"recipient_id" => self.id}],
        :created_at.gt=>7.days.ago).order_by([:created_at,:asc]).distinct(:from_to_stamp).to_a.map! do |msg|
          msg.gsub(self.id.to_s,"").gsub(/\-/,"")
        end.uniq

    # Find responding users
    unless message_pairs.empty?
      # Users must be in range
      users = User.where(:_id.in => message_pairs).where(:loc => {"$within" => {
        "$centerSphere" => [self.loc,((self.swap_range.fdiv(1000)).fdiv(6371))
      ]}})

      # Map last_message to each user
      return users.map do |user|
        user.define_singleton_method :last_message do
          Message.first(conditions: {'$or' =>
            [{"sender_id" => self.id},{"recipient_id" => self.id}]},
            sort:[[:created_at,:asc]])
        end
        user
      end.sort_by!(&:last_message).reverse!
    end

    # Empty
    []
  end

  def remove_chat recipient

  
  end

  # Calculate channels
  def chats_OLD
  	# 1. Messages where current_user is sender or recipient
  	# 2. Grouped by recipent
  	senders = Message.any_of({sender_id: self.id},{recipient_id: self.id })
  		.where(:created_at.gt=> 7.days.ago)
	  	.asc(:created_at)
	  	.distinct(:recipient_id)
#	  	.only(:sender_id, :recipient_id)


  	# 3. Who is inside users swap
  	inside_sphere = User.where(:_id.in => senders).where(:loc => {
	  	"$within" => {
		  	"$centerSphere" => [
			  	self.loc,
			  	((self.swap_range.fdiv(1000)).fdiv(6371))
			]
		}
	  }).to_a.map(&:id)

    # "$centerSphere" => [self.loc, ((range.fdiv(1000)).fdiv(6371))]


  	# 4. Add inside_swap attribute to sender
  	senders.to_a.map do |sender|
  		sender = User.find(sender)

  		sender["inside_swap"] = false		
  		sender["inside_swap"] = true if sender.id.in? inside_sphere
  		
  		if sender.id == self.id
  			nil
  		else
  			sender
  		end

  	end.compact!

  end

  # Set name from nicname/name mess
  def self.name_from_provider auth
    if auth["provider"] == "facebook"
      if !auth["info"].nil? && !auth["info"]["nickname"].nil?
        auth["info"]["nickname"]
      elsif !auth["info"].nil? && !auth["info"]["first_name"].nil?
        auth["info"]["first_name"]
      else
        nil
      end
    elsif auth["provider"] == "twitter"
      if !auth["info"].nil? && !auth["info"]["nickname"].nil?
        auth["info"]["nickname"]
      else
        nil
      end
    elsif auth["provider"] == "google_oauth2"
      if !auth["info"].nil? && !auth["info"]["name"].nil?
        auth["info"]["name"]
      else
        nil
      end
    else
      nil
    end
  end

  # Set custom image for user
  def image= value
    self.image_custom = value
    write_attribute :image_custom, value
  end

  # Set birthday
  def birthday= value
    self.birthday_custom = value
    write_attribute :birthday_custom, value
  end

  # Set gender
  def gender= value
    value=nil if value.nil? or value=="" or value=="none"
    self.gender_custom = value
    write_attribute :gender_custom, value
  end

  # Get image for user from image_path if set otherwise from providers
  def image
    return self.image_custom unless self.image_custom.nil?
    return nil if self.providers.size == 0
    images = self.providers.map(&:image).compact
    return images.first if !images.empty?
    nil
  end

  # Big image of user profile
  def big_image
    return image.gsub(/square/i, "large") if image =~ /facebook/ && image =~ /square/
    return image.gsub(/normal/i, "original") if image =~ /twitter/ && image =~ /normal/
    image
  end

  # User birthday
  def birthday
    return self.birthday_custom unless self.birthday_custom.nil?
    return nil if self.providers.size == 0
    birthdays = self.providers.map(&:birthday).compact
    return birthdays.first if !birthdays.empty?
    nil
  end

  # User age
  def age
    return 0 if birthday.nil?
    DateTime.now.year-birthday.year
  end

  # Set birthday to 1.1.year
  def age= value
    value = DateTime.now.year-value.to_i
    self.birthday=DateTime.strptime("#{value}-1-1", "%Y-%m-%d")
  end

  # Get gender for user
  def gender

    if self.providers.size == 0
      return self.gender_custom
    end

    if self.gender_custom != "none"
      return self.gender_custom
    end

    return nil if self.providers.size == 0
    genders = self.providers.map(&:gender).compact
    return genders.first if !genders.empty?
    nil    
  end

  # Find or create user from omniauth
  def self.find_or_create auth
    current_location = nil

    if auth["provider"] =~ /(facebook|twitter|google_oauth2)/i
      provider = Provider.new(
        :provider => auth["provider"],
        :uid => auth["uid"],
        :name => User.name_from_provider(auth)
      )

      # debugger

      # If provider provides image
      if auth["provider"] == "facebook"
        if !auth["info"].nil? && !auth["info"]["image"].nil?
          provider.image = ["http://graph.facebook.com/",
            provider.uid,"/picture?type=square"].join('') #50x50
        end
      end

      if auth["provider"] == "twitter"

app/views/app/user/_member_profile.haml
.distance_between{:class => @user.gender}
	=link_to "#profile-title" do
		- if current_user != @user
			%span.who
				= @user
				is
				= @user.distance_between_to_human current_user
			from your location
		- else
			This is you.

- if not(@user.status.nil?) and @user.status != ""
	.user_status{:class => @user.gender}
		.user_status_wrap
			= @user.status	

.member_profile_wrap
	- if current_user != @user
		.profile_tools
			=link_to chat_path(@user), :remote => true do
				.chat_wrap
					=image_tag 'chat.png'

			-if current_user.can_notify?(@user)
				.notify_wrap
					=link_to notify_path(@user), :remote => true do
						=image_tag 'notify.png'

	- if not(@user.image.nil?) and @user.image != ""
		.big_image
			=image_tag @user.big_image, :alt => @user.to_s

app/views/app/user/_profile.html.haml
.stat=render "app/stat"

.profile_header{:class=>(current_user.gender=="" or current_user.gender.nil?)? "none": current_user.gender }

	.live_status_field
		=render partial:"app/user/status_field", locals:{user: user}

	.status_tools
		- if !user.image.nil?
			.profile_image_wrap=image_tag user.image, width:48, height:48
			
		.tools
			.status
				=link_to "Update satus", status_form_path, :remote => true, :class => "update_status_link"

				%span.buttonz
					=link_to "Save", "#status_save"
					|
					=link_to "Cancel", "#status_cancel"
			.loc
				=link_to "Refresh location", "#refresh_location"
			
			-if user.from_facebook?
				.share.fb
					=link_to raw('Share location on <span class="fb">Facebook</span>!'), share_location_path(provider:"facebook"), remote:true, class: "share_location"

			-if user.from_twitter?
				.share.tw
					=link_to raw('Share location on <span class="tw">Twitter</span>!'), share_location_path(provider:"twitter"), remote:true, class: "share_location"					
%ul
	%li.name
		%span.label Name
		%span.value=user.name
	%li.age
		%span.label Age
		%span.value.selector
			=form_for current_user, :url => profile_update_path, :remote => true do |f|
				
				.left=link_to "Left", "#left"

				.current=user.age
				=f.text_field :age, :class => "current_value"

				.right=link_to "Right", "#Right"
				.values
					%ul
						- (0..100).each do |i|
							%li{class: "v_#{i}"}=i
	%li.gender
		%span.label Gender
		%span.value.selector
			=form_for current_user, :url => profile_update_path, :remote => true do |f|
				.left=link_to "Left", "#left"
				
				.current=(user.gender.nil? or user.gender.to_s == "none")? "UFO": user.gender

				=f.text_field :gender, :class => "current_value"

				.right=link_to "Right", "#Right"
				.values
					%ul
						%li{class: "v_female"}="FEMALE"
						%li{class: "v_"}="UFO"
						%li{class: "v_male"}="MALE"
	%li.swap_range
		%span.label Radddar swoop
		%span.value.selector
			=form_for current_user, :url => profile_update_path, :remote => true do |f|
				.left=link_to "Left", "#left"
				
				.current
					=number_to_human(user.swap_range,:units => :distance_short)
				=f.text_field :swap_range, :class => "current_value"
				
				.right=link_to "Right", "#Right"
				.values
					%ul
						- User.allowed_swap_ranges.each do |range|
							%li{class: "v_#{range}"}
								=number_to_human(range,:units => :distance_short)

	%li.logout
		%span.label=link_to "Logout", signout_path

app/views/app/user/_status_field.html.haml
-if !user.status.nil? and user.status!=""
	.status_field
		%p=user.status

app/views/app/user/_status_form.haml
.set_status_form
	=form_for current_user, :url => status_set_path, :remote => true do |f|

		- if f.object.errors.any?
			- f.object.errors.full_messages.each do |error|
				%span.error=error

		=f.text_area :status, :rows => 3

app/views/app/user/notify.js.erb
$(".tabs .notify_wrap").fadeOut("slow");

app/views/app/user/profile.js.erb
$(".tabs .member_profile").html('<%= j render "app/user/member_profile" %>');
<% if @user.loc? %>
RadddarMap.move_to_user(<%= raw @user.to_json %>);
<% end %>

app/views/app/user/share_location.js.erb
var pre_text_html = $(".status_tools .share a").html();

$(".status_tools .share a").text("Location shared!");

var pre_text_set = setTimeout(function(){
	$(".status_tools .share a").html(pre_text_html);
},2000);

app/views/app/user/status_form.js.erb
$(".live_status_field").html('<%= j render "app/user/status_form" %>');

$(".live_status_field form textarea").focus();

$(".status_tools .buttonz").show();
$(".status_tools div.status").addClass("open");

app/views/app/user/status_reload.js.erb
$(".live_status_field").html('<%= j render(partial:"app/user/status_field", locals:{user:current_user}) %>');

$(".status_tools .buttonz").hide();
$(".status_tools div.status").removeClass("open");