config/routes.rb
Radddar::Application.routes.draw do

  root :to => "app#landing"
  match '/reminder', :to => "app#reminder", :as => "reminder"

  match '/app', :to => "app#app", :as => "app"
  match '/live', :to => "app#live", :as => "live"

  match '/auth/:provider/callback', :to => 'sessions#callback', :as => "auth"
  match '/signout', :to => 'sessions#destroy', :as => 'signout'
  match '/auth', :to => "sessions#pusher_auth", :as => "pusher_auth"

  match '/current_user', :to => "app#current_user_action", :as => "current_user"
  match '/profile_update', :to => "app#profile_update", :as => "profile_update"
  
  match '/status_form', :to => "app#status_form", :as => "status_form"
  match '/status_set', :to => "app#status_set", :as => "status_set"
  match '/status_reload', :to => "app#status_reload", :as => "status_reload"

  match '/share/location/:provider', :to => "app#share_location", :as => "share_location"

  match '/profile/:id', :to => "app#profile", :as => "profile"
  match '/swap', :to => "app#swap", :as => "swap"

  match '/notify/:id', :to => "app#notify", :as => "notify"
  match '/remove_note/:stamp', :to => "app#remove_note", :as => "remove_note"

  match '/reload_chat_feed', :to => "app#reload_chat_feed", :as => "reload_chat_feed"
  
  match '/chat/:id', :to => "app#chat", :as => "chat"
  match '/message/:id', :to => "app#message", :as => "message"

  match '/reload_clients/:key', :to => "app#reload_clients", :as => "reload_clients"

  match '/wisdom-script.ttf', :to => "app#wisdom_script"
  match '/steelfish.ttf', :to => "app#steelfish"

  match '/:id', :to => "app#public_radddar", :as => "public_radddar"

end

app/views/app/_about.html.haml
%h1 About RADDDAR

%p
	Raddddar is a web based app where you can easily see and connect with people around you. It’s a service based on coincidence and location. Just a simple opportunity, to meet people near you.

.social_links
	%ul
		%li.facebook
			%a(href="http://www.facebook.com/pages/Radddar/259375980765458") Radddar @ Facebook
		%li.twitter
			%a(href="http://twitter.com/myradddar") MyRadddar @ Twitter

%p.foot
	=link_to "VBG d.o.o.", "http://www.vbg.si", :target => "_new"
	and
	=link_to "OPALAB d.o.o.", "http://opalab.com", :target => "_new"

app/views/app/_alpha_form.haml
.alpha_form
	%ul
		%li.facebook
			=link_to "Login with Facebook", "/auth/facebook"
		%li.twitter
			=link_to "Login with Twitter", "/auth/twitter"
		%li.google
			=link_to "Login with Google", "/auth/google_oauth2"

app/views/app/_landing_facebook.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=203564286383182";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/app/_landing_twitter.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-via="myradddar">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/app/_reminder_form.haml
=form_for @reminder, :remote => true, :url => reminder_path do |f|
	- unless f.object.email.nil?
		=f.text_field :email
	- else
		=f.text_field :email, :value => "your email please"

- if @reminder.errors.any?
	- @reminder.errors.full_messages.each do |msg|
		%p.error="#{msg}!"

- if @reminder.valid?
	%p.info Thanks for your email!

app/views/app/_stat.haml
.stat-wrap
	=link_to "#swap_stat" do
		=humanize_stat(current_user.swap_stat)

app/views/app/app.html.haml
#map=" "

-# #map{:style=>"display:none"}=" "

#app
	.slogan
		=image_tag "radddar_slogan.png"
	.tabs-nav
		%ul
			%li.back
				%a(href="#back") BACK
			%li.member_profile{:style => "display:none;"}
				%a(href="#member_profile") MEMBER PROFILE
			%li.chats{:style => "display:none;"}
				%a(href="#member_profile") CHATS	
			%li.chat
				%a(href="#chat")
					.alerts_wrap
						%span.alerts=0
					%span CHAT
			%li.radddar
				%a.active(href="#radddar")
					.alerts_wrap
						%span.alerts=0
					%span RADDDAR
			%li.profile
				%a(href="#profile") PROFILE
			%li.about
				%a(href="#about") ABOUT

	.tabs
		.chat.screen=render "app/chat/list"
		.radddar.screen.active=render "app/map/list"
		.profile.screen=render partial:"app/user/profile", locals:{user: current_user}
		.member_profile.screen
			%p Loading...
		.chats.screen
			.chats-wrap
				%ul.live-chat-list=" "
		.about.screen=render "app/about"

#global_error
	.msg-wrap
		.msg
			Darn now you broke it. It seems you are unplugged. Radddar has lost you. We can't find you on our satelite eather. Please make sure you are loged in and have location anabled.
			%br/
			%br/
			%strong=link_to "... or reload RADDDAR.", app_path

app/views/app/landing.html.haml
!!!
%html
	%head
		%title RADDDAR - Who's on your?

		= stylesheet_link_tag    "landing", :media => "all"
		= javascript_include_tag "landing"
		= csrf_meta_tags

		%link{:rel=>"shortcut icon", :href=>asset_path("radddar_icon.png")}


		%meta(property="fb:admins" content="571988676,1014463747")
		%meta(property="fb:app_id" content="203564286383182")
		%meta(property="og:title" content="RADDDAR - Who's on your?")
		%meta(property="og:type" content="website")
		%meta(property="og:url" content="http://www.radddar.com")

		%meta{:property=>"og:image", :content=>image_path("radddar-big.jpg")}

		%meta(property="og:description" content="Raddddar is a web based app where you can easily see and connect with people around you. It’s a service based on coincidence and location. Just a simple opportunity, to meet people near you.")

		%meta(name="apple-mobile-web-app-capable" content="yes")
		%meta(name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no")

		-if Rails.env == "production"
			=render partial: "layouts/google_analytics"

	%body
		-if Rails.env == "production"
			=render partial: 'landing_facebook'

		.video.off
			.video-wrap
				-# 
					%iframe(width="853" height="480" src="http://www.youtube.com/embed/ApHpgL5aQYk?rel=0" frameborder="0" allowfullscreen)=""
				
				%embed(id="ytplayer" width="853" height="480" allowfullscreen="true" allowscriptaccess="always" quality="high" bgcolor="#000000" name="ytplayer" style="" src="http://www.youtube.com/v/ApHpgL5aQYk?enablejsapi=1&version=3&playerapiid=ytplayer" type="application/x-shockwave-flash")

				%a.video-toggle(href="#video-toggle") Close video

		.wrap
			.inner_wrap
				.logo=link_to "RADDDAR - Who's on your?", root_url
				.play_video
					%a.video-toggle(href="#video-toggle") See the video
				.content
					.left
						.left-wrap
							.about-out-wrap
								%h1
									What is it
								%p
									Raddddar is a web based app where you can easily see and connect with people around you. It’s a service based on coincidence and location. Just a simple opportunity, to meet people near you.

							.release-wrap
								%h1 Alpha Release
								.reminder-wrap=render "alpha_form"

							.reminder-out-wrap
								%h1 Get updates
								.reminder-wrap.reminder=render "reminder_form"

					.center
						.center-wrap#screens
							%ul{:style=> "width:#{5*212}px"}
								%li.active=image_tag "radddar_mockup_7-02-1.jpg"
								%li=image_tag "radddar_mockup_7-03-1.jpg"
								%li=image_tag "radddar_mockup_7-04-1.jpg"
								%li=image_tag "radddar_mockup_7-05-1.jpg"
								%li=image_tag "radddar_mockup_7-06-1.jpg"
					.right
						.right-wrap
							%ul
								%li No feed.
								%li No followers.
								%li No walls.
								%li No personal details.
								%li Free.
			.footer
				.footer-wrap
					%table{:style=>"margin:0 auto; border-collapse:collapse"}
						%tr
							%td{:style => "padding-top:5px;"}
								-if Rails.env == "production"
									=render partial: 'landing_twitter'
								-else
									%span [landing_twitter]
							%td
								-if Rails.env == "production"
									%div(class="fb-like" data-href="http://www.facebook.com/pages/Radddar/259375980765458" data-send="false" data-layout="button_count" data-width="80" data-show-faces="true" data-colorscheme="dark")=" "
								-else
									%span [facebook]
							%td

								\/
								=link_to "Twitter","http://twitter.com/myradddar"
								\/
								=link_to "Facebook", "http://www.facebook.com/pages/Radddar/259375980765458"
								\/
							%td
								&copy;
								=link_to "VBG", "http://www.vbg.si"
							%td
								\/
								=mail_to "info@radddar.com", "Contact", :encode => "javascript"

		-#
			-unless signed_in?
				=link_to "Facebook login", "/auth/facebook"
				|
				=link_to "Twitter login", "/auth/twitter"

app/views/app/live.html.haml
%h1 RADDDAR Live

%h2 Users

%table
	- @users.sort_by!(&:updated_at).each do |user|
		%tr
			%td=image_tag user.image
			%td=user
			%td=user.updated_at
			

app/views/app/public_radddar.html.haml
!!!
%html

	-#
		<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# radddardev: http://ogp.me/ns/fb/radddardev#">
		<meta property="fb:app_id"                     content="371033286241287" /> 
		<meta property="og:type"                       content="radddardev:radddar" /> 
		<meta property="og:url"                        content="Put your own URL to the object here" /> 
		<meta property="og:title"                      content="Sample Radddar" /> 
		<meta property="og:image"                      content="https://s-static.ak.fbcdn.net/images/devsite/attachment_blank.png" /> 
		<meta property="radddardev:location:latitude"  content="46.5573993" /> 
		<meta property="radddardev:location:longitude" content="15.645982" /> 

	%head{prefix:"og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# #{FB["ns"]}: http://ogp.me/ns/fb/#{FB["ns"]}#"}
		%title="RADDDAR of #{@user.name}."

		= stylesheet_link_tag    "landing", :media => "all"
		= javascript_include_tag "radddar_public"
		= csrf_meta_tags

		%link{:rel=>"shortcut icon", :href=>asset_path("radddar_icon.png")}


		%meta(property="fb:admins" content="571988676,1014463747")

		%meta{property:"fb:app_id", content:"#{FB["app_id"]}"}
		%meta{property: "og:title", content: "RADDDAR of #{@user}."}
		%meta{property: "og:type", content: "#{FB["ns"]}:radddar"}
		%meta{property: "og:url", content: public_radddar_url(@user)}

		%meta{:property=>"og:image", :content=>image_path("radddar-big.jpg")}

		%meta{property:"og:description", content:strip_tags(humanize_stat_for_3rd(@user,@user.swap_stat))}

		- if @user.loc?
			%meta{property:"#{FB["ns"]}:location:latitude",  content:@user.loc.first}
			%meta{property:"#{FB["ns"]}:location:longitude", content:@user.loc.last}

		%meta{property: "#{FB["ns"]}:gender", content: @user.gender_str }
		%meta{property: "#{FB["ns"]}:user_image", content: @user.image }
		%meta{property: "#{FB["ns"]}:name", content: @user.name }

		%meta(name="apple-mobile-web-app-capable" content="yes")
		%meta(name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no")

		=javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCFWhDn4H02EWwneGYcGjnxYMtTsf5Hkc0&sensor=false"
		

		-if Rails.env == "production"
			=render partial: "layouts/google_analytics"

	%body
		-if Rails.env == "production"
			=render partial: 'landing_facebook'


		.wrap.public_radddar
			.inner_wrap
				.logo=link_to "RADDDAR - Who's on your?", root_url
				.content
					.left

						.top-wrap
							.top
								="#{@user}."
								=humanize_stat_for_3rd(@user,@user.swap_stat)

						.map-wrap
							#map=""

						.about
							.about-out-wrap
								%h1
									What is it
								%p
									Raddddar is a web based app where you can easily see and connect with people around you. It’s a service based on coincidence and location. Just a simple opportunity, to meet people near you.


						.visit-wrap
							.visit
								=link_to "Try it. It's free!", root_path

			.footer
				.footer-wrap
					%table{:style=>"margin:0 auto; border-collapse:collapse"}
						%tr
							%td{:style => "padding-top:5px;"}
								-if Rails.env == "production"
									=render partial: 'landing_twitter'
								-else
									%span [landing_twitter]
							%td
								-if Rails.env == "production"
									%div(class="fb-like" data-href="http://www.facebook.com/pages/Radddar/259375980765458" data-send="false" data-layout="button_count" data-width="80" data-show-faces="true" data-colorscheme="dark")=" "
								-else
									%span [facebook]
							%td

								\/
								=link_to "Twitter","http://twitter.com/myradddar"
								\/
								=link_to "Facebook", "http://www.facebook.com/pages/Radddar/259375980765458"
								\/
							%td
								&copy;
								=link_to "VBG", "http://www.vbg.si"
							%td
								\/
								=mail_to "info@radddar.com", "Contact", :encode => "javascript"

		-#
			-unless signed_in?
				=link_to "Facebook login", "/auth/facebook"
				|
				=link_to "Twitter login", "/auth/twitter"

app/views/app/reminder.js.erb
$(".reminder").html('<%= j render "reminder_form" %>');