config/routes.rb
Radddar::Application.routes.draw do

  root :to => "app#landing"
  match '/reminder', :to => "app#reminder", :as => "reminder"

  match '/app', :to => "app#app", :as => "app"
  match '/live', :to => "app#live", :as => "live"

  match '/auth/:provider/callback', :to => 'sessions#callback', :as => "auth"
  match '/signout', :to => 'sessions#destroy', :as => 'signout'
  match '/auth', :to => "sessions#pusher_auth", :as => "pusher_auth"

  match '/current_user', :to => "app#current_user_action", :as => "current_user"
  match '/profile_update', :to => "app#profile_update", :as => "profile_update"
  
  match '/status_form', :to => "app#status_form", :as => "status_form"
  match '/status_set', :to => "app#status_set", :as => "status_set"
  match '/status_reload', :to => "app#status_reload", :as => "status_reload"

  match '/share/location/:provider', :to => "app#share_location", :as => "share_location"

  match '/profile/:id', :to => "app#profile", :as => "profile"
  match '/swap', :to => "app#swap", :as => "swap"

  match '/notify/:id', :to => "app#notify", :as => "notify"
  match '/remove_note/:stamp', :to => "app#remove_note", :as => "remove_note"

  match '/reload_chat_feed', :to => "app#reload_chat_feed", :as => "reload_chat_feed"
  
  match '/chat/:id', :to => "app#chat", :as => "chat"
  match '/message/:id', :to => "app#message", :as => "message"

  match '/reload_clients/:key', :to => "app#reload_clients", :as => "reload_clients"

  match '/wisdom-script.ttf', :to => "app#wisdom_script"
  match '/steelfish.ttf', :to => "app#steelfish"

  match '/:id', :to => "app#public_radddar", :as => "public_radddar"

end

app/views/app/chat/_chat_feed.haml
- @feed = current_user.feed
- if !@feed[:notes].empty? or !@feed[:chats].empty?
	.users
		%ul
			- @feed[:chats].each do |user_with_chat| 
				%li.chat.user{user_with_chat.to_data.merge!(:class=>[user_with_chat.gender,"off"])}
					.user_line_wrap

						-unless user_with_chat.image.nil?
							.image=link_to image_tag(user_with_chat.image), "#user-#{user_with_chat.id}"

						.details
							.name
								=link_to "#user-#{user_with_chat.id}" do
									=user_with_chat.to_s
									%span.created_at
										\-
										=time_ago_in_words user_with_chat.last_message.created_at
										ago
						
						.alerts_wrap
							%span.alerts=0


						=link_to "Chat with #{user_with_chat}", chat_path(user_with_chat), :remote => true, :class => "tools"

						-#
							.remove=link_to "Remove", remove_note_path(user_with_chat.stamp), :method => :delete, :remote => true

			- @feed[:notes].each do |user_with_note|
				%li.note.user{user_with_note.to_data.merge!(:class=>[user_with_note.gender, "off" ])}
					.user_line_wrap

						-unless user_with_note.image.nil?
							.image
								=link_to image_tag(user_with_note.image), "#user-#{user_with_note.id}"

						.details
							.name
								=link_to "#user-#{user_with_note.id}" do
									=user_with_note.to_s
									%span.created_at
										\-
										=time_ago_in_words user_with_note.notified_at
										ago
						
						.tools="Note"

						.remove=link_to "Remove", remove_note_path(user_with_note.stamp), :method => :delete, :remote => true
- else
	%p.no_chats
		Sorry friend. You haven't exchanged any interactions yet.

app/views/app/chat/_list.html.haml
.stat=render "app/stat"
.chat_feed.list
	= render "app/chat/chat_feed"

app/views/app/chat/_message.haml
- if message.valid?
	%li{:class => ["message", ((message.from==current_user.id.to_s)? "mine": "their")] }
		%span.created_at=message_time message
		\-
		%span.body=message.body

app/views/app/chat/_message_form.haml
.message-form-wrap
	=form_for @message, :url => message_path(@user), :remote => true do |f|
		- if f.object.errors.any?
			- f.object.errors.full_messages.each do |error|
				%span.error=error

		=f.submit "Send", :class => "send"
		=f.text_area :body, :rows => 2, :class => "message_body"

app/views/app/chat/_messages.haml
.top_info
	YOU AND
	%span{:class => @user.gender_str}=@user

.chats-wrap
	.messages
		%ul
			- @messages.reverse.each do |message|
				= render :partial => "app/chat/message", :locals => {:message => message}

app/views/app/chat/chat.js.erb
RadddarChat.open_chat(<%= raw @user.to_json %>,
'<%= j render "app/chat/messages" %>',
'<%= j render "app/chat/message_form" %>',
<% if @jump.to_i == 1 %>
true
<% else %>
false
<% end %>);

app/views/app/chat/message.js.erb
RadddarChat.message_sent(<%= raw @user.to_json %>,
'<%= j render :partial => "app/chat/message", :locals => {:message => @message} %>',
'<%= j render "app/chat/message_form" %>');

app/views/app/chat/reload_chat_feed.js.erb
$(".tabs .chat_feed").html("<%= j render 'app/chat/chat_feed' %>");

Status.update_swap(function(){ });

app/views/app/chat/remove_note.js.erb
remove_note